"""Resolve the Home Assistant requirements our integration pulls in at import time.

Walks the "dependencies" of our manifest.json through the manifests of the installed
homeassistant and prints their "requirements" as a pip requirements file, so that
tests/requirements_test.txt only needs to pin pytest-homeassistant-custom-component.

Usage: python tests/gen_requirements.py [--output requirements_ha.txt]
"""

import argparse
import importlib.metadata
import importlib.util
import json
import re
import sys
from collections import deque
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OWN_MANIFEST = REPO_ROOT / "custom_components" / "divoom" / "manifest.json"

# usb imports aioesphomeapi without declaring it, real installs get it through esphome.
# Only the requirements of these domains are taken, no recursion.
EXTRA_REQUIREMENT_DOMAINS = ("esphome",)


def fail(message):
    print(f"error: {message}", file=sys.stderr)
    raise SystemExit(1)


def ha_components_dir():
    """Locate homeassistant/components without importing homeassistant, which needs the
    POSIX-only fcntl."""
    spec = importlib.util.find_spec("homeassistant")
    if spec is None or spec.origin is None:
        fail("homeassistant is not installed - run 'pip install -r tests/requirements_test.txt' first")

    components = Path(spec.origin).parent / "components"
    if not components.is_dir():
        fail(f"no components directory at {components}")

    return components


def check_python_version():
    """Warn early when HA raised its minimum Python above what the workflows use."""
    requires = importlib.metadata.metadata("homeassistant").get("Requires-Python")
    if not requires:
        return

    for lower_bound in re.findall(r">=\s*([\d.]+)", requires):
        required = tuple(int(part) for part in lower_bound.rstrip(".").split("."))
        if sys.version_info[: len(required)] < required:
            fail(
                f"homeassistant requires Python {requires}, "
                f"but this is {'.'.join(str(part) for part in sys.version_info[:3])}"
            )


def read_manifest(path, what):
    if not path.is_file():
        fail(f"no manifest for {what} at {path} - did Home Assistant rename or remove it?")

    return json.loads(path.read_text(encoding="utf-8"))


def collect(components, seeds):
    """Breadth-first walk over the dependency closure, gathering requirements."""
    requirements = set()
    queue = deque(seeds)
    seen = set(seeds)

    while queue:
        domain = queue.popleft()
        manifest = read_manifest(components / domain / "manifest.json", f"domain '{domain}'")
        requirements.update(manifest.get("requirements", []))

        for dependency in manifest.get("dependencies", []):
            if dependency not in seen:
                seen.add(dependency)
                queue.append(dependency)

    return requirements, seen


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--output", type=Path, help="write to this file instead of stdout")
    args = parser.parse_args()

    check_python_version()
    components = ha_components_dir()
    own = read_manifest(OWN_MANIFEST, "the divoom integration")

    seeds = own.get("dependencies", [])
    requirements, visited = collect(components, seeds)
    requirements.update(own.get("requirements", []))

    for domain in EXTRA_REQUIREMENT_DOMAINS:
        manifest = read_manifest(components / domain / "manifest.json", f"extra domain '{domain}'")
        requirements.update(manifest.get("requirements", []))

    version = importlib.metadata.version("homeassistant")
    lines = [
        "# Generated by tests/gen_requirements.py - do not commit.",
        f"# homeassistant=={version}, resolved from {', '.join(sorted(visited))}",
        f"# plus requirements of {', '.join(EXTRA_REQUIREMENT_DOMAINS)} and of the divoom manifest.",
        *sorted(requirements, key=str.lower),
        "",
    ]
    text = "\n".join(lines)

    if args.output:
        args.output.write_text(text, encoding="utf-8")
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
