clock:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    clock:
      example: 1
      selector:
        number:
          min: 0
          max: 15
          mode: box
    twentyfour:
      example: true
      selector:
        boolean:
    weather:
      example: false
      selector:
        boolean:
    temp:
      example: false
      selector:
        boolean:
    calendar:
      example: true
      selector:
        boolean:
    color:
      example: [250, 0, 0]
      selector:
        color_rgb:
    hot:
      example: false
      selector:
        boolean:

light:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    brightness:
      example: 75
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider
    color:
      example: [250, 0, 0]
      selector:
        color_rgb:

"on":
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom

"off":
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom

brightness:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    brightness:
      required: true
      example: 100
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider

image:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    file:
      required: true
      example: "ha16.gif"
      selector:
        text:
    time:
      example: 100
      selector:
        number:
          min: 0
          max: 65535
          unit_of_measurement: ms
          mode: box

text:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    text:
      required: true
      example: "Hi Divoom"
      selector:
        text:
    font:
      example: "divoom.ttf"
      selector:
        text:
    size:
      example: 16
      selector:
        number:
          min: 1
          unit_of_measurement: px
          mode: box
    time:
      example: 100
      selector:
        number:
          min: 0
          max: 65535
          unit_of_measurement: ms
          mode: box
    foreground_color:
      example: [250, 0, 0]
      selector:
        color_rgb:
    background_color:
      example: [0, 0, 0]
      selector:
        color_rgb:

design:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    number:
      example: 2
      selector:
        number:
          min: 0
          max: 255
          mode: box

effects:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    number:
      required: true
      example: 2
      selector:
        number:
          min: 0
          max: 255
          mode: box

visualization:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    number:
      required: true
      example: 2
      selector:
        number:
          min: 0
          max: 255
          mode: box
    foreground_color:
      example: [250, 0, 0]
      selector:
        color_rgb:
    background_color:
      example: [0, 0, 0]
      selector:
        color_rgb:

signal:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    number:
      required: true
      example: 2
      selector:
        number:
          min: 0
          max: 255
          mode: box

alarm:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    number:
      example: 0
      selector:
        number:
          min: 0
          max: 255
          mode: box
    value:
      example: "07:30:00"
      selector:
        time:
    weekday:
      example: [mon, tue, wed, thu, fri]
      selector:
        select:
          multiple: true
          translation_key: weekday
          options:
            - mon
            - tue
            - wed
            - thu
            - fri
            - sat
            - sun
    alarmmode:
      example: 0
      selector:
        number:
          min: 0
          max: 255
          mode: box
    triggermode:
      example: 0
      selector:
        number:
          min: 0
          max: 255
          mode: box
    frequency:
      example: 100.3
      selector:
        number:
          min: 64
          max: 108
          step: 0.1
          unit_of_measurement: MHz
          mode: box
    volume:
      example: 75
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider

countdown:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    value:
      required: true
      example: true
      selector:
        boolean:
    countdown:
      example: "01:30:00"
      selector:
        time:

timer:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    value:
      required: true
      example: true
      selector:
        boolean:

memorial:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    number:
      example: 0
      selector:
        number:
          min: 0
          max: 255
          mode: box
    value:
      example: "2000-12-31 00:00:00"
      selector:
        datetime:
    text:
      example: "Happy New Year!"
      selector:
        text:

scoreboard:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    player1:
      example: 2
      selector:
        number:
          min: 0
          max: 65535
          mode: box
    player2:
      example: 1
      selector:
        number:
          min: 0
          max: 65535
          mode: box

noise:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    value:
      required: true
      example: true
      selector:
        boolean:

sleep:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    value:
      required: true
      example: true
      selector:
        boolean:
    time:
      example: 30
      selector:
        number:
          min: 0
          max: 255
          unit_of_measurement: min
          mode: box
    sleepmode:
      example: 4
      selector:
        number:
          min: 0
          max: 255
          mode: box
    frequency:
      example: 100.3
      selector:
        number:
          min: 64
          max: 108
          step: 0.1
          unit_of_measurement: MHz
          mode: box
    volume:
      example: 10
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider
    color:
      example: [255, 255, 0]
      selector:
        color_rgb:
    brightness:
      example: 50
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider

datetime:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    value:
      example: "2024-12-31 18:30:00"
      selector:
        datetime:

equalizer:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    number:
      required: true
      example: 2
      selector:
        number:
          min: 0
          max: 255
          mode: box
    audiomode:
      example: true
      selector:
        boolean:
    backgroundmode:
      example: false
      selector:
        boolean:
    streammode:
      example: false
      selector:
        boolean:

volume:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    volume:
      required: true
      example: 75
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider

playstate:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    value:
      required: true
      example: true
      selector:
        boolean:

radio:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    value:
      required: true
      example: true
      selector:
        boolean:
    frequency:
      example: 100.3
      selector:
        number:
          min: 64
          max: 108
          step: 0.1
          unit_of_measurement: MHz
          mode: box

lyrics:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom

keyboard:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    value:
      required: true
      example: next
      selector:
        select:
          translation_key: keyboard_value
          options:
            - previous
            - toggle
            - next

game:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    value:
      example: 2
      selector:
        number:
          min: 0
          max: 255
          mode: box

gamecontrol:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    value:
      required: true
      example: go
      selector:
        select:
          translation_key: gamecontrol_value
          options:
            - go
            - left
            - right
            - up
            - down
            - ok

weather:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    value:
      required: true
      example: 25
      selector:
        number:
          step: 1
          mode: box
    unit:
      example: "°C"
      selector:
        select:
          translation_key: temperature_unit
          options:
            - "°C"
            - "°F"
    weather:
      example: rainy
      selector:
        select:
          custom_value: true
          translation_key: weather_condition
          options:
            - clear-night
            - cloudy
            - exceptional
            - fog
            - hail
            - lightning
            - lightning-rainy
            - partlycloudy
            - pouring
            - rainy
            - snowy
            - snowy-rainy
            - sunny
            - windy
            - windy-variant

temperature:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    value:
      example: "°C"
      selector:
        select:
          translation_key: temperature_unit
          options:
            - "°C"
            - "°F"
    color:
      example: [250, 0, 0]
      selector:
        color_rgb:

raw:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
    raw:
      required: true
      example: [0x74, 0x64]
      selector:
        object:

connect:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom

disconnect:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: divoom
