name: Test Suite

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.13"
      - name: "Install test requirements"
        run: pip install -r tests/requirements_test.txt
      - name: "Run pytest"
        env:
          PYTHONPATH: "tests"
        run: pytest tests
